## 4. Modelling
### 4.2 Model training

In [352]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns
#importing the PCA scaling library
from sklearn.decomposition import PCA
#importing the feature scaling library
from sklearn.preprocessing import StandardScaler
#Import Sklearn package's data splitting function which is based on random function
from sklearn.model_selection import train_test_split
# Import Linear Regression, Ridge and Lasso machine learning library
from sklearn.linear_model import LogisticRegression
# Import KNN Regressor machine learning library
from sklearn.tree import DecisionTreeClassifier
# Import ensemble machine learning library
from sklearn.ensemble import (RandomForestRegressor, GradientBoostingRegressor,AdaBoostRegressor,BaggingRegressor)
# Import support vector regressor machine learning library
from sklearn.svm import SVC
#Import the metrics
from sklearn import metrics
#Import the Voting regressor for Ensemble
from sklearn.ensemble import VotingRegressor
# Import stats from scipy
from scipy import stats
# Import zscore for scaling
from scipy.stats import zscore
#importing the metrics
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score
#importing the K fold
from sklearn.model_selection import KFold
#importing the cross validation score
from sklearn.model_selection import cross_val_score
#importing the preprocessing library
from sklearn import preprocessing
# importing the Polynomial features
from sklearn.preprocessing import PolynomialFeatures
from sklearn.utils import resample
from sklearn.svm import SVC
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

In [353]:
# Uploading data file
loan_main_dummies = pd.read_csv('./loan_main_dummies.csv')
loan_main_dummies.head()

,loan_amnt,funded_amnt,term,installment,grade,sub_grade,emp_length,annual_inc,issue_d,dti,...,purpose_home_improvement,purpose_house,purpose_major_purchase,purpose_medical,purpose_moving,purpose_other,purpose_renewable_energy,purpose_small_business,purpose_vacation,purpose_wedding
0,5000.0,5000.0,36,162.87,1,6,10,24000.0,2011,27.65,...,0,0,0,0,0,0,0,0,0,0
1,2500.0,2500.0,60,59.83,2,13,0,30000.0,2011,1.00,...,0,0,0,0,0,0,0,0,0,0
2,2400.0,2400.0,36,84.33,2,14,10,12252.0,2011,8.72,...,0,0,0,0,0,0,0,1,0,0
3,10000.0,10000.0,36,339.31,2,10,10,49200.0,2011,20.00,...,0,0,0,0,0,1,0,0,0,0
4,3000.0,3000.0,60,67.79,1,9,1,80000.0,2011,17.94,...,0,0,0,0,0,1,0,0,0,0

In [354]:
loan_main_dummies.head()

,loan_amnt,funded_amnt,term,installment,grade,sub_grade,emp_length,annual_inc,issue_d,dti,...,purpose_home_improvement,purpose_house,purpose_major_purchase,purpose_medical,purpose_moving,purpose_other,purpose_renewable_energy,purpose_small_business,purpose_vacation,purpose_wedding
0,5000.0,5000.0,36,162.87,1,6,10,24000.0,2011,27.65,...,0,0,0,0,0,0,0,0,0,0
1,2500.0,2500.0,60,59.83,2,13,0,30000.0,2011,1.00,...,0,0,0,0,0,0,0,0,0,0
2,2400.0,2400.0,36,84.33,2,14,10,12252.0,2011,8.72,...,0,0,0,0,0,0,0,1,0,0
3,10000.0,10000.0,36,339.31,2,10,10,49200.0,2011,20.00,...,0,0,0,0,0,1,0,0,0,0
4,3000.0,3000.0,60,67.79,1,9,1,80000.0,2011,17.94,...,0,0,0,0,0,1,0,0,0,0

In [355]:
# Define dataset
X = loan_main_dummies.drop('loan_status', axis =1)
y = loan_main_dummies.loan_status

In [356]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state = 1)

In [357]:
# some features are very skew, I'll normalize them
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
X_train = pd.DataFrame(X_train, columns= X.columns)
X_test = pd.DataFrame(X_test, columns = X.columns)

In [358]:
X_train.shape

(29774, 52)

In [359]:
X_test.shape

(12761, 52)

In [360]:
y_train.shape

(29774,)

In [361]:
y_test.shape

(12761,)

In [362]:
X_train.describe()

,loan_amnt,funded_amnt,term,installment,grade,sub_grade,emp_length,annual_inc,issue_d,dti,...,purpose_home_improvement,purpose_house,purpose_major_purchase,purpose_medical,purpose_moving,purpose_other,purpose_renewable_energy,purpose_small_business,purpose_vacation,purpose_wedding
count,2.977400e+04,2.977400e+04,2.977400e+04,2.977400e+04,2.977400e+04,2.977400e+04,2.977400e+04,2.977400e+04,2.977400e+04,2.977400e+04,...,2.977400e+04,2.977400e+04,2.977400e+04,2.977400e+04,2.977400e+04,2.977400e+04,2.977400e+04,2.977400e+04,2.977400e+04,2.977400e+04
mean,-7.249860e-16,-1.301102e-16,-5.485376e-16,7.983434e-18,2.908006e-16,9.763765e-17,-3.104068e-17,1.238868e-16,1.113873e-13,6.122745e-18,...,-5.990521e-16,1.118895e-15,1.067826e-16,4.839803e-16,9.485762e-16,5.640980e-16,3.929089e-15,1.140581e-15,2.945470e-15,7.797812e-16
std,1.000017e+00,1.000017e+00,1.000017e+00,1.000017e+00,1.000017e+00,1.000017e+00,1.000017e+00,1.000017e+00,1.000017e+00,1.000017e+00,...,1.000017e+00,1.000017e+00,1.000017e+00,1.000017e+00,1.000017e+00,1.000017e+00,1.000017e+00,1.000017e+00,1.000017e+00,1.000017e+00
min,-1.431832e+00,-1.445065e+00,-5.933057e-01,-1.467418e+00,-1.163396e+00,-1.474521e+00,-1.330257e+00,-2.372500e+00,-3.355429e+00,-1.989699e+00,...,-2.831555e-01,-9.830880e-02,-2.389354e-01,-1.346231e-01,-1.249915e-01,-3.411531e-01,-4.991575e-02,-2.197033e-01,-9.743437e-02,-1.575332e-01
25%,-7.966980e-01,-8.159841e-01,-5.933057e-01,-7.511920e-01,-4.661967e-01,-7.651754e-01,-7.757999e-01,-7.658013e-01,-2.418447e-01,-7.636866e-01,...,-2.831555e-01,-9.830880e-02,-2.389354e-01,-1.346231e-01,-1.249915e-01,-3.411531e-01,-4.991575e-02,-2.197033e-01,-9.743437e-02,-1.575332e-01
50%,-1.885911e-01,-1.781664e-01,-5.933057e-01,-2.169955e-01,-4.661967e-01,-1.976990e-01,-2.213432e-01,-3.153997e-02,7.960169e-01,1.650326e-02,...,-2.831555e-01,-9.830880e-02,-2.389354e-01,-1.346231e-01,-1.249915e-01,-3.411531e-01,-4.991575e-02,-2.197033e-01,-9.743437e-02,-1.575332e-01
75%,5.276237e-01,5.819724e-01,1.685472e+00,5.050927e-01,9.282018e-01,6.535156e-01,1.164798e+00,6.028248e-01,7.960169e-01,7.892627e-01,...,-2.831555e-01,-9.830880e-02,-2.389354e-01,-1.346231e-01,-1.249915e-01,-3.411531e-01,-4.991575e-02,-2.197033e-01,-9.743437e-02,-1.575332e-01
max,3.230321e+00,3.377885e+00,1.685472e+00,4.691065e+00,3.019800e+00,3.349029e+00,1.442027e+00,2.688601e+00,7.960169e-01,2.467042e+00,...,3.531628e+00,1.017203e+01,4.185232e+00,7.428146e+00,8.000546e+00,2.931235e+00,2.003376e+01,4.551593e+00,1.026332e+01,6.347868e+00

### Logistic Regression

In [363]:
model_LR = LogisticRegression(max_iter=10000)
model_LR.fit(X_train, y_train)
model_LR.score(X_test,y_test)

0.8651359611315728

In [364]:
prediction_LR = model_LR.predict(X_test)
print('Performance on training data using Logistic Regression:',model_LR.score(X_train,y_train))
print('Performance on test data using Logistic Regression:',model_LR.score(X_test,y_test))
acc_LR = accuracy_score(y_test, prediction_LR)
#recall_LR = recall_score(y_test, prediction_LR)
#precision_LR = precision_score(y_test, prediction_LR)
#f1_LR = f1_score(y_test, prediction_LR)
AUROC_LR = roc_auc_score(y_test, prediction_LR)

Performance on training data using Logistic Regression: 0.862295962920669
Performance on test data using Logistic Regression: 0.8651359611315728

In [365]:
confusion_matrix(y_test, prediction_LR)

array([[  506,  1380],
       [  341, 10534]])

In [366]:
results_1 = pd.DataFrame({'Model':['Logistic Regression'], 'Accuracy': [acc_LR],  'AUROC': AUROC_LR},index={'1'})
results_1= results_1[['Model', 'Accuracy', 'AUROC']]
results_1

                 Model  Accuracy     AUROC
1  Logistic Regression  0.865136  0.618468

In [367]:
num_folds = 10
kfold = KFold(n_splits=num_folds, shuffle=True, random_state = 77)
resultsLR = cross_val_score(model_LR,X, y, cv=kfold)
acc_KF_LR=np.mean(abs(resultsLR))
AUROC_KF_LR = np.mean(abs(cross_val_score(model_LR, X, y, scoring='roc_auc', cv=10)))
#recall_KF_LR = np.mean(abs(cross_val_score(model_LR, X, y, scoring='recall', cv=10)))
#precision_KF_LR = np.mean(abs(cross_val_score(model_LR, X, y, scoring='precision', cv=10)))
#f1_KF_LR = np.mean(abs(cross_val_score(model_LR, X, y, scoring='f1', cv=10)))

In [368]:
tempResultsDf  = pd.DataFrame({'Model':['Logistic Regression KFold'], 'Accuracy': [acc_KF_LR], 'AUROC': AUROC_KF_LR},index={'2'})
# 'Recall': recall_KF_LR, 'Precision': precision_KF_LR, 'F1-score': f1_KF_LR,
results_1 = pd.concat([results_1, tempResultsDf ])
results_1 = results_1[['Model', 'Accuracy', 'AUROC']]
results_1

                       Model  Accuracy     AUROC
1        Logistic Regression  0.865136  0.618468
2  Logistic Regression KFold  0.857576  0.856344

### K Nearest Neighbors (KNN)

In [369]:
model_KN = KNeighborsClassifier(n_neighbors=10)
model_KN.fit(X_train,y_train)
model_KN.score(X_test, y_test)

0.8508737559752371

In [370]:
prediction_KN = model_KN.predict(X_test)
print('Performance on training data using KNeighbors:',model_KN.score(X_train,y_train))
print('Performance on test data using KNeighbors:',model_KN.score(X_test,y_test))
acc_KN = accuracy_score(y_test, prediction_KN)
#recall_KN = recall_score(y_test, prediction_KN)
#precision_KN = precision_score(y_test, prediction_KN)
#f1_KN = f1_score(y_test, prediction_KN)
AUROC_KN = roc_auc_score(y_test, prediction_KN)

Performance on training data using KNeighbors: 0.8677033653523208
Performance on test data using KNeighbors: 0.8508737559752371

In [371]:
tempResultsDf  = pd.DataFrame({'Model':['K Nearest Neighbors'], 'Accuracy': [acc_KN], 'AUROC': AUROC_KN},index={'3'})
results_1 = pd.concat([results_1, tempResultsDf ])
results_1 = results_1[['Model', 'Accuracy', 'AUROC']]
results_1

                       Model  Accuracy     AUROC
1        Logistic Regression  0.865136  0.618468
2  Logistic Regression KFold  0.857576  0.856344
3        K Nearest Neighbors  0.850874  0.571094

In [372]:
confusion_matrix(y_test, prediction_KN)

array([[  328,  1558],
       [  345, 10530]])

In [373]:
num_folds = 10
kfold = KFold(n_splits=num_folds, shuffle=True, random_state = 77)
resultsKN = cross_val_score(model_KN, X, y, cv=kfold)
acc_KF_KN = np.mean(abs(resultsKN))
AUROC_KF_KN = np.mean(abs(cross_val_score(model_KN, X, y, scoring='roc_auc', cv=10)))
#recall_KF_KN = np.mean(abs(cross_val_score(model_KN, X, y, scoring='recall', cv=10)))
#precision_KF_KN = np.mean(abs(cross_val_score(model_KN, X, y, scoring='precision', cv=10)))
#f1_KF_KN = np.mean(abs(cross_val_score(model_KN, X, y, scoring='f1', cv=10)))

In [374]:
tempResultsDf  = pd.DataFrame({'Model':['K Nearest Neighbors KFold'], 'Accuracy': [acc_KF_KN], 'AUROC': AUROC_KF_KN},index={'4'})
results_1 = pd.concat([results_1, tempResultsDf ])
results_1 = results_1[['Model', 'Accuracy', 'AUROC']]
results_1

                       Model  Accuracy     AUROC
1        Logistic Regression  0.865136  0.618468
2  Logistic Regression KFold  0.857576  0.856344
3        K Nearest Neighbors  0.850874  0.571094
4  K Nearest Neighbors KFold  0.831456  0.690629

### Random Forest

In [376]:
model_RF = RandomForestClassifier(n_estimators=100)
model_RF.fit(X_train, y_train)
model_RF.score(X_test, y_test)

0.884883629809576

In [377]:
prediction_RF = model_RF.predict(X_test)
print('Performance on training data using RandomForest Classifier:',model_RF.score(X_train,y_train))
print('Performance on testing data using RandomForest Classifier:',model_RF.score(X_test,y_test))
acc_RF = accuracy_score(y_test, prediction_RF)
#recall_RF = recall_score(y_test, prediction_RF)
#precision_RF = precision_score(y_test, prediction_RF)
#f1_RF = f1_score(y_test, prediction_RF)
AUROC_RF = roc_auc_score(y_test, prediction_RF)

Performance on training data using RandomForest Classifier: 1.0
Performance on testing data using RandomForest Classifier: 0.884883629809576

In [378]:
tempResultsDf = pd.DataFrame({'Model':['Random Forest'], 'Accuracy': [acc_RF], 'AUROC': AUROC_RF}, index={'5'})
results_1 = pd.concat([results_1, tempResultsDf])
results_1 = results_1[['Model', 'Accuracy', 'AUROC']]
results_1

                       Model  Accuracy     AUROC
1        Logistic Regression  0.865136  0.618468
2  Logistic Regression KFold  0.857576  0.856344
3        K Nearest Neighbors  0.850874  0.571094
4  K Nearest Neighbors KFold  0.831456  0.690629
5              Random Forest  0.884884  0.682427

In [379]:
confusion_matrix(y_test, prediction_RF)

array([[  745,  1141],
       [  328, 10547]])

In [380]:
num_folds = 10
kfold = KFold(n_splits=num_folds, shuffle=True, random_state = 77)
resultsRF = cross_val_score(model_RF,X, y, cv=kfold)
acc_KF_RF = np.mean(abs(resultsRF))
AUROC_KF_RF = np.mean(abs(cross_val_score(model_RF, X, y, scoring='roc_auc', cv=10)))
#recall_KF_RF = np.mean(abs(cross_val_score(model_RF, X, y, scoring='recall', cv=10)))
#precision_KF_RF = np.mean(abs(cross_val_score(model_RF, X, y, scoring='precision', cv=10)))
#f1_KF_RF = np.mean(abs(cross_val_score(model_RF, X, y, scoring='f1', cv=10)))

In [381]:
tempResultsDf = pd.DataFrame({'Model':['RandomForest KFold'], 'Accuracy': [acc_KF_RF], 'AUROC': AUROC_KF_RF}, index={'6'})
results_1 = pd.concat([results_1, tempResultsDf])
results_1 = results_1[['Model', 'Accuracy', 'AUROC']]
results_1

                       Model  Accuracy     AUROC
1        Logistic Regression  0.865136  0.618468
2  Logistic Regression KFold  0.857576  0.856344
3        K Nearest Neighbors  0.850874  0.571094
4  K Nearest Neighbors KFold  0.831456  0.690629
5              Random Forest  0.884884  0.682427
6         RandomForest KFold  0.883743  0.898013

### Ada Boosting Classifier

In [382]:
model_AB = AdaBoostClassifier(random_state=1)
model_AB.fit(X_train, y_train)
model_AB.score(X_test,y_test)

0.8852754486325523

In [383]:
prediction_AB = model_AB.predict(X_test)
print('Performance on training data using AdaBoosting Classifier:',model_AB.score(X_train,y_train))
print('Performance on testing data using AdaBoosting Classifier:',model_AB.score(X_test,y_test))
acc_AB = accuracy_score(y_test, prediction_AB)
recall_AB = recall_score(y_test, prediction_AB)
precision_AB = precision_score(y_test, prediction_AB)
f1_AB = f1_score(y_test, prediction_AB)
AUROC_AB = roc_auc_score(y_test, prediction_AB)

Performance on training data using AdaBoosting Classifier: 0.8827164640290186
Performance on testing data using AdaBoosting Classifier: 0.8852754486325523

In [384]:
confusion_matrix(y_test, prediction_AB)

array([[  860,  1026],
       [  438, 10437]])

In [386]:
tempResultsDf= pd.DataFrame({'Model':['AdaBoost Classifier'], 'Accuracy': [acc_AB], 'AUROC': AUROC_AB}, index={'7'})
results_1 = pd.concat([results_1, tempResultsDf])
results_1 = results_1[['Model', 'Accuracy', 'AUROC']]
results_1

                       Model  Accuracy     AUROC
1        Logistic Regression  0.865136  0.618468
2  Logistic Regression KFold  0.857576  0.856344
3        K Nearest Neighbors  0.850874  0.571094
4  K Nearest Neighbors KFold  0.831456  0.690629
5              Random Forest  0.884884  0.682427
6         RandomForest KFold  0.883743  0.898013
7        AdaBoost Classifier  0.885275  0.707858

In [387]:
num_folds = 10
kfold = KFold(n_splits=num_folds, shuffle=True, random_state = 77)
resultsAB = cross_val_score(model_AB,X, y, cv=kfold)
acc_KF_AB =np.mean(abs(resultsAB))
AUROC_KF_AB = np.mean(abs(cross_val_score(model_AB, X, y, scoring='roc_auc', cv=10)))
#recall_KF_AB = np.mean(abs(cross_val_score(model_AB, X, y, scoring='recall', cv=10)))
#precision_KF_AB = np.mean(abs(cross_val_score(model_AB, X, y, scoring='precision', cv=10)))
#f1_KF_AB = np.mean(abs(cross_val_score(model_AB, X, y, scoring='f1', cv=10)))

In [388]:
tempResultsDf = pd.DataFrame({'Model':['AdaBoost KFold'], 'Accuracy': [acc_KF_AB], 'AUROC': AUROC_KF_AB,}, index={'8'})
results_1 = pd.concat([results_1, tempResultsDf])
results_1 = results_1[['Model', 'Accuracy', 'AUROC']]
results_1

                       Model  Accuracy     AUROC
1        Logistic Regression  0.865136  0.618468
2  Logistic Regression KFold  0.857576  0.856344
3        K Nearest Neighbors  0.850874  0.571094
4  K Nearest Neighbors KFold  0.831456  0.690629
5              Random Forest  0.884884  0.682427
6         RandomForest KFold  0.883743  0.898013
7        AdaBoost Classifier  0.885275  0.707858
8             AdaBoost KFold  0.881086  0.903117

### Gradient Boosting Classifier

In [389]:
model_GB= GradientBoostingClassifier(learning_rate=0.01, random_state=1)
model_GB.fit(X_train, y_train)
model_GB.score(X_test,y_test)

0.8529895776193088

In [390]:
prediction_GB = model_GB.predict(X_test)
print('Performance on training data using Gradient Boosting Classifier:',model_GB.score(X_train,y_train))
print('Performance on test data using Gradient Boosting Classifier:',model_GB.score(X_test,y_test))
acc_GB = accuracy_score(y_test, prediction_GB)
recall_GB = recall_score(y_test, prediction_GB)
precision_GB = precision_score(y_test, prediction_GB)
f1_GB = f1_score(y_test, prediction_GB)
AUROC_GB = roc_auc_score(y_test, prediction_GB)

Performance on training data using Gradient Boosting Classifier: 0.8484248001612145
Performance on test data using Gradient Boosting Classifier: 0.8529895776193088

In [391]:
confusion_matrix(y_test, prediction_GB)

array([[   10,  1876],
       [    0, 10875]])

In [392]:
tempResultsDf = pd.DataFrame({'Model':['Gradient Boosting Classifier'], 'Accuracy': [acc_GB], 'AUROC': AUROC_GB}, index={'9'})
results_1 = pd.concat([results_1, tempResultsDf])
results_1 = results_1[['Model', 'Accuracy', 'AUROC']]
results_1

                          Model  Accuracy     AUROC
1           Logistic Regression  0.865136  0.618468
2     Logistic Regression KFold  0.857576  0.856344
3           K Nearest Neighbors  0.850874  0.571094
4     K Nearest Neighbors KFold  0.831456  0.690629
5                 Random Forest  0.884884  0.682427
6            RandomForest KFold  0.883743  0.898013
7           AdaBoost Classifier  0.885275  0.707858
8                AdaBoost KFold  0.881086  0.903117
9  Gradient Boosting Classifier  0.852990  0.502651

In [393]:
num_folds = 10
kfold = KFold(n_splits=num_folds, shuffle=True, random_state = 77)
resultsGB = cross_val_score(model_GB,X, y, cv=kfold)
acc_KF_GB =np.mean(abs(resultsGB))
AUROC_KF_GB = np.mean(abs(cross_val_score(model_GB, X, y, scoring='roc_auc', cv=10)))
#recall_KF_GB = np.mean(abs(cross_val_score(model_GB, X, y, scoring='recall', cv=10)))
#precision_KF_GB = np.mean(abs(cross_val_score(model_GB, X, y, scoring='precision', cv=10)))
#f1_KF_GB = np.mean(abs(cross_val_score(model_GB, X, y, scoring='f1', cv=10)))

In [394]:
tempResultsDf = pd.DataFrame({'Model':['Gradient Boosting KFold'], 'Accuracy': [acc_KF_GB], 'AUROC': AUROC_KF_GB}, index={'10'})
results_1 = pd.concat([results_1, tempResultsDf])
results_1 = results_1[['Model', 'Accuracy', 'AUROC']]
results_1

                           Model  Accuracy     AUROC
1            Logistic Regression  0.865136  0.618468
2      Logistic Regression KFold  0.857576  0.856344
3            K Nearest Neighbors  0.850874  0.571094
4      K Nearest Neighbors KFold  0.831456  0.690629
5                  Random Forest  0.884884  0.682427
6             RandomForest KFold  0.883743  0.898013
7            AdaBoost Classifier  0.885275  0.707858
8                 AdaBoost KFold  0.881086  0.903117
9   Gradient Boosting Classifier  0.852990  0.502651
10       Gradient Boosting KFold  0.849747  0.850584

In [395]:
results_1

                           Model  Accuracy     AUROC
1            Logistic Regression  0.865136  0.618468
2      Logistic Regression KFold  0.857576  0.856344
3            K Nearest Neighbors  0.850874  0.571094
4      K Nearest Neighbors KFold  0.831456  0.690629
5                  Random Forest  0.884884  0.682427
6             RandomForest KFold  0.883743  0.898013
7            AdaBoost Classifier  0.885275  0.707858
8                 AdaBoost KFold  0.881086  0.903117
9   Gradient Boosting Classifier  0.852990  0.502651
10       Gradient Boosting KFold  0.849747  0.850584

In [396]:
results_1.sort_values(['AUROC'])

                           Model  Accuracy     AUROC
9   Gradient Boosting Classifier  0.852990  0.502651
3            K Nearest Neighbors  0.850874  0.571094
1            Logistic Regression  0.865136  0.618468
5                  Random Forest  0.884884  0.682427
4      K Nearest Neighbors KFold  0.831456  0.690629
7            AdaBoost Classifier  0.885275  0.707858
10       Gradient Boosting KFold  0.849747  0.850584
2      Logistic Regression KFold  0.857576  0.856344
6             RandomForest KFold  0.883743  0.898013
8                 AdaBoost KFold  0.881086  0.903117